site_name: Jonnycake.Tech
title: Developer Portfolio & Blog
description: Tech projects, experience, tips, tricks, and more
gtag: G-YVTGX6JF66
permalink: /:year/:month/:day/:title
markdown: kramdown
canonical: https://jonnycake.tech
#resume_link: #PDF

socials:
  - name: GitHub
    label: github
    url: https://github.com/Jonnycake/
    icon: fa fa-github
  - name: LinkedIn
    label: linkedin
    url: https://www.linkedin.com/in/jonnycake
    icon: fa fa-linkedin
  - name: TryHackMe
    label: tryhackme
    url: https://tryhackme.com/p/Jonnycake
    icon: tryhackme-logo

collections:
  posts:
    output: true
  projects:
    output: true
  upcoming:
    output: true

defaults:
  - values:
      layout: default
  - scope:
      type: "projects"
    values:
      layout: project
  - scope:
      type: "posts"
    values:
      layout: post
  - scope:
      type: "upcoming"
    values:
      layout: upcoming-post
